### PR TITLE
Access additional license data

### PR DESCRIPTION
**Pull request by pavelmemory**
The change in this PR addresses a problem described in the [issue "Make license database public"](https://github.com/go-enry/go-license-detector/issues/16).
In order to get access to additional license data the two new exportable functions were added:
- LicenseURLs -  it returns a list of URLs where the license can be found in the internet
- LicenseName - it returns the full name of the license
The values are get from the JSON representation of the license stored in the https://github.com/spdx/license-list-data/archive/v$(SPDX_DATA_VERSION).tar.gz as all other information about the licenses. But to get the fully qualified URLs the third column was added to the urls.csv file and it contains schema of the URL. That is done to have possibility re-build the full URL and do not change existing format of the second column that may be used by someone already.
Both functions return a new `ErrUnknownLicenseID` error in case the license ID provided as a parameter doesn't exist in the database.

The change also includes upgrade of the SPDX_DATA_VERSION to the latest at the moment 3.17 version. After the update the tool begun to panic because of the index access to the empty slice. The fix has been applied to solve that issue.
After the upgrade the expected confidence in the tests were adjusted to the new results.

The one question that remains open here is why `.mit-license.org` literal is used in the `licensedb/internal/assets/extract_urls.go`? Should it be changed to the `://mit-license.org` to have a proper URL format?

### CODE REVIEW

**Comment by pavelmemory** [comment]
@bzz could you please take a look at this PR?
Unfortunately the list of maintainers doesn't exist by the [reference](https://github.com/go-enry/go-license-detector/blob/master/MAINTAINERS.md) that is mentioned in the [Contributing Guidelines](https://github.com/go-enry/go-license-detector/blob/master/CONTRIBUTING.md#contributing-guidelines)

**Review by lafriks — APPROVED** [review]

**Comment by pavelmemory** [comment]
Hi @lafriks! Thanks for taking an eye on my changes. Could you please explain why `.mit-license.org` is used instead of `://mit-license.org` (the last paragraph in the PR description)?

**Review by vmarkovtsev — APPROVED** [review]
Thanks for the contribution!

**Comment by pavelmemory** [comment]
Seems like [Lint](https://github.com/go-enry/go-license-detector/runs/7470488827?check_suite_focus=true) job fails because `golangci/golangci-lint-action` needs to be updated or the configuration needs to be changed to use the newer version of the [golangci-lint](https://github.com/golangci/golangci-lint). I don't have permissions for doing this, so I rely on maintainers of the repository to do this.

**Comment by vmarkovtsev** [comment]
I don't think I have ever supported windows, it's ok to remove the CI checks for that OS.

**Comment by pavelmemory** [comment]
> I don't think I have ever supported windows, it's ok to remove the CI checks for that OS.

@vmarkovtsev I have removed Windows OS from the actions, hope the CI will pass this time.

**Comment by To1ne** [comment]
Hey @vmarkovtsev, is there anything we can do to help get this PR over the finish line? @pavelmemory made the necessary changes to drop CI for Windows (this would actually close #22).

**Comment by lafriks** [comment]
API seems to be backward compatible as only adds new methods so v4.4.0 way to go

**Comment by bzz** [comment]
Closed&re-opened to trigger the CI, going to merge as soon as it passes. 
Then rebase #24 -> ✅  -> 🔪 v4.4.0

**Pull request closed without merging**
