### PR TITLE
Feature/add scan file content

### PR DESCRIPTION
**Pull request by ninnymuggins97**
In this PR I exposed a previously private function used to scan the file and find license content. I believe this is a very useful enhancement as it provides the user the option to pass file content directly instead of directory paths. This is useful in batch processing on a larger scale and avoids the workaround of having to create and delete directories to use the tool. :-)

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
Actually it should probably be moved to `licensedb` folder directly

**Comment by ninnymuggins97** [comment]
Updated :-)

**Review by lafriks — APPROVED** [review]

**Comment by grantsavage** [comment]
Is there a timeline on when this change can be merged in? I would like to utilize this functionality as well.

**Comment by lafriks** [comment]
@bzz ping

**Review by bzz — APPROVED** [review]
Sorry for the delay, looks great to me.

Would merging be enough, or shall we also release a new version ?

**Comment by grantsavage** [comment]
I think releasing a new version would be beneficial! 😃

**Pull request merged**
